SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usp_getAllReligionInXML]

AS
SET NOCOUNT ON;

	DECLARE @XML XML = (select ReligionID AS ID, ReligionName AS Name from dbo.tb_religion FOR XML PATH('Type'), ROOT('Religion'));
	SELECT @XML AS [XML] WHERE LEN(CONVERT(VARCHAR(MAX), @XML)) > 0;
	

SET NOCOUNT OFF;
GO
