SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[usp_removeUser]
(@USERID VARCHAR(50))
AS
SET NOCOUNT ON;

IF EXISTS (SELECT * FROM dbo.tb_Users WHERE UserID = @USERID)
BEGIN
	UPDATE dbo.tb_Users SET Deleted = 1 WHERE UserID = @USERID
END

SELECT @@ROWCOUNT AS Result

SET NOCOUNT OFF;

GO
