SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usp_getAllRaceInXML]

AS
SET NOCOUNT ON;

	DECLARE @XML XML = (select RaceID AS ID, RaceName AS Name from dbo.tb_race FOR XML PATH('Type'), ROOT('Race'));
	SELECT @XML AS [XML] WHERE LEN(CONVERT(VARCHAR(MAX), @XML)) > 0;
	

SET NOCOUNT OFF;
GO
