SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usp_getAllRoleInXML]

AS
SET NOCOUNT ON;

	DECLARE @XML XML = (select RoleID, RoleName from dbo.tb_Roles FOR XML PATH('Role'), ROOT('ChurchRole'));
	SELECT @XML AS [XML] WHERE LEN(CONVERT(VARCHAR(MAX), @XML)) > 0;
	

SET NOCOUNT OFF;
GO
