CREATE TABLE [dbo].[tb_members]
(
[Salutation] [tinyint] NOT NULL,
[EnglishName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ChineseName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_ChineseName] DEFAULT (''),
[DOB] [date] NOT NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NRIC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Nationality] [tinyint] NOT NULL,
[Dialect] [tinyint] NOT NULL CONSTRAINT [DF_tb_members_Dialect] DEFAULT ((0)),
[MaritalStatus] [tinyint] NOT NULL,
[MarriageDate] [date] NULL,
[AddressStreet] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AddressHouseBlk] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AddressPostalCode] [int] NOT NULL,
[AddressUnit] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_AddressUnit] DEFAULT (''),
[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_Email] DEFAULT (''),
[Education] [tinyint] NOT NULL,
[Language] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Occupation] [tinyint] NOT NULL,
[HomeTel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_HomeTel] DEFAULT (''),
[MobileTel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_MobileTel] DEFAULT (''),
[BaptismDate] [date] NULL CONSTRAINT [DF_tb_members_BaptismDate] DEFAULT (''),
[BaptismBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_BaptismBy] DEFAULT (''),
[BaptismByOthers] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_BaptismByOthers] DEFAULT (''),
[BaptismChurch] [tinyint] NOT NULL CONSTRAINT [DF_tb_members_BaptismChurch] DEFAULT ((0)),
[BaptismChurchOthers] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_BaptismChurchOthers] DEFAULT (''),
[ConfirmDate] [date] NULL,
[ConfirmBy] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_ConfirmBy] DEFAULT (''),
[ConfirmByOthers] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_ConfirmByOthers] DEFAULT (''),
[ConfirmChurch] [tinyint] NOT NULL CONSTRAINT [DF_tb_members_ConfirmChurch] DEFAULT ((0)),
[ConfirmChurchOthers] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_ConfirmChurchOthers] DEFAULT (''),
[TransferReason] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_TransferReason] DEFAULT (''),
[Family] [xml] NOT NULL CONSTRAINT [DF_tb_members_Family] DEFAULT ('<FamilyList></FamilyList>'),
[Child] [xml] NOT NULL CONSTRAINT [DF_tb_members_Child] DEFAULT ('<ChildList></ChildList>'),
[CurrentParish] [tinyint] NOT NULL CONSTRAINT [DF_tb_members_CurrentParish] DEFAULT ((0)),
[ICPhoto] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PreviousChurch] [tinyint] NOT NULL CONSTRAINT [DF_tb_members_PreviousChurch] DEFAULT ((0)),
[PreviousChurchOthers] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_PreviousChurchOthers] DEFAULT (''),
[DeceasedDate] [date] NULL,
[CreatedDate] [date] NOT NULL CONSTRAINT [DF_tb_members_CreatedDate] DEFAULT (getdate()),
[CarIU] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tb_members_CarIU] DEFAULT (''),
[ReceiveMailingList] [bit] NOT NULL CONSTRAINT [DF_tb_members_ReceiveMailingList] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[tb_members] ADD CONSTRAINT [PK_tb_members] PRIMARY KEY CLUSTERED  ([NRIC]) ON [PRIMARY]
GO
